workflows:
  ios_release:
    name: iOS Release Workflow
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install # Ensure CocoaPods dependencies are installed
      - name: Build iOS
        script: |
          npx react-native run-ios --configuration Release # Build iOS app
    artifacts:
      - build/ios/*.ipa # Path to the generated IPA file

  android_release:
    name: Android Release Workflow
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd android && ./gradlew clean # Clean previous builds (if necessary)
      - name: Build APK/AAB
        script: |
          cd android && ./gradlew assembleRelease # Build APK/AAB
    artifacts:
      - build/android/app/build/outputs/bundle/release/*.aab # Path to the generated AAB file
      - build/android/app/build/outputs/apk/release/*.apk # Path to the generated APK file
