workflows:
  default:
    name: Build and Deploy Android AAB
    max_build_duration: 60  # Optional: define a max build time (in minutes)
    environment:
      java: 11  # 👈 Add this here to ensure Gradle uses Java 11
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install jetifier  # Make sure jetifier is installed before using it
          npx jetify  # Ensure Android dependencies are compatible

      - name: Make gradlew executable
        script: |
          chmod +x android/gradlew  # Grant permission to gradlew script

      - name: Build AAB
        script: |
          cd android
          ./gradlew clean
          ./gradlew bundleRelease  # Builds the AAB file

      - name: Upload AAB as Artifact
        script: |
          mkdir -p $CM_BUILD_DIR/aab_output
          cp android/app/build/outputs/bundle/release/app-release.aab $CM_BUILD_DIR/aab_output/

    artifacts:
      - aab_output/*  # Ensure the AAB file is uploaded as an artifact
