name: Build Android AAB

on:
  push:
    branches:
      - master # Trigger build when pushing to the main branch
  pull_request:
    branches:
      - master  # Trigger build when there is a pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          npx jetify  # This is to ensure Android dependencies are compatible

      - name: Build AAB
        run: |
          cd android
          ./gradlew clean
          ./gradlew bundleRelease  # Builds the AAB file

      - name: Upload AAB as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
