name: Android AAB Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: cd android && ./gradlew bundleRelease
      - uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: android/app/build/outputs/bundle/release/app-release.aab
